spring:
  application:
    name: idpay-reward-calculator
  config:
    activate:
      on-profile: default
  cloud:
    stream:
      function:
        definition: trxProducer;trxProcessor;trxConsumerReward
      bindings:
        trxProcessor-in-0:
          destination: ${KAFKA_REWARD_TOPIC_RTD_TRX:}
          group: ${KAFKA_IDPAY_GROUP:}
          content-type: ${KAFKA_CONTENT_TYPE:}
          binder: ${KAFKA_BINDER:}
        trxProcessor-out-0:
          destination: ${KAFKA_REWARD_TOPIC_REWARD_TRX:}
          content-type: ${KAFKA_CONTENT_TYPE:}
          binder: ${KAFKA_BINDER:}
        trxConsumerReward-in-0:
          destination: ${KAFKA_REWARD_TOPIC_REWARD_TRX:}
          group: ${KAFKA_IDPAY_GROUP:}
          content-type: ${KAFKA_CONTENT_TYPE:}
          binder: ${KAFKA_BINDER:}
        trxProducer-out-0:
          destination: ${KAFKA_REWARD_TOPIC_RTD_TRX:}
          content-type: ${KAFKA_CONTENT_TYPE:}
          binder: ${KAFKA_BINDER:}
      kafka:
        binder:
          auto-create-topics: ${KAFKA_REWARD_BINDER_AUTO_CREATE_TOPIC}
          brokers: ${KAFKA_BINDER_BROKER_ENDPOINT_LIST:}
          configuration:
            heartbeat.interval.ms: ${KAFKA_REWARD_BINDER_CONFIGURATION_HEARTBEAT_INTERVAL_MS:}
            session.timeout.ms: ${KAFKA_REWARD_BINDER_CONFIGURATION_SESSION_TIMEOUT_MS:}
            sasl:
              jaas:
                config: ${KAFKA_REWARD_SASL_JAAS_CONFIG:}
              mechanism: ${KAFKA_REWARD_SASL_MECHANISM:}
            security:
              protocol: ${KAFKA_REWARD_SECURITY_PROTOCOL:}
          consumerProperties:
            key:
              deserializer: ${KAFKA_DESERIALIZER_TYPE:}
            value:
              deserializer: ${KAFKA_DESERIALIZER_TYPE:}
            socket:
              connection:
                setup:
                  timeout:
                    max:
                      ms: ${KAFKA_REWARD_CONNECTION_TIMEOUT_MAX_MS:}
                    ms: ${KAFKA_REWARD_CONNECTION_TIMEOUT_MS:}
            connections:
              max:
                idle:
                  ms: ${KAFKA_REWARD_CONNECTIONS_MAX_IDLE_MS:}
