import it.gov.pagopa.model.RewardTransaction
import java.util.Map
import java.math.BigDecimal;

function BigDecimal calculator (BigDecimal amount, int percent){
    return  amount.multiply(new BigDecimal(percent)).divide(new BigDecimal(100));
}

rule "ini001 - Calculate prize for transaction"
    agenda-group "ini001"
    when
        trx : RewardTransaction(hpan=="5c6bda1b1f5f6238dcba70f9f4b5a77671eb2b1563b0ca6d15d14c649a9b7ce0")
    then
        System.out.println(trx.getRewards());
end

rule "ini002 - Calculate prize for transaction"
    agenda-group "ini002"
    when
        trx : RewardTransaction(hpan=="5c6bda1b1f5f6238dcba70f9f4b5a77671eb2b1563b0ca6d15d14c649a9b7ce0")
    then
        trx.getRewards().put("ini0002",calculator(trx.getAmount(),40));
end
rule "ini003 - Calculate prize for transaction"
    agenda-group "ini003"
    when
        trx : RewardTransaction(hpan=="5c6bda1b1f5f6238dcba70f9f4b5a77671eb2b1563b0ca6d15d14c649a9b7ce0")
    then
        trx.getRewards().put("ini0003",calculator(trx.getAmount(),50));
end

rule "ini004 - Calculate prize for transaction"
    agenda-group "ini004"
    when
        trx : RewardTransaction(hpan=="5c6bda1b1f5f6238dcba70f9f4b5a77671eb2b1563b0ca6d15d14c649a9b7ce0")
    then
        trx.getRewards().put("ini0004",calculator(trx.getAmount(),60));
end
