import it.gov.pagopa.model.RewardTransaction
import java.math.BigDecimal;

function BigDecimal calculator (BigDecimal amount, int percent){
    return  amount.multiply(new BigDecimal(percent)).divide(new BigDecimal(100));
}

rule "Calculate prize for transaction"
    when
        trx : RewardTransaction(hpan=="5c6bda1b1f5f6238dcba70f9f4b5a77671eb2b1563b0ca6d15d14c649a9b7ce0")
    then
        trx.setReward(calculator(trx.getAmount(),30));
end
