microservice-chart:
  image:
    repository: cstarucommonacr.azurecr.io/idpayrewardcalculator
    tag: latest
    pullPolicy: Always

  ingress:
    host: "uat01.idpay.internal.uat.cstar.pagopa.it"

    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1.5Gi"
      cpu: "750m"


  autoscaling:
    enable: true
    minReplica: 4
    maxReplica: 4
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    aks-api-url: cstar-u-weu-uat01-aks-apiserver-url
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-u-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}

  envConfig:
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:+UseContainerSupport
      -Djava.security.egd=file:/dev/./urandom
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 
      -Dio.netty.eventLoopThreads=100
      -javaagent:/app/applicationinsights-agent.jar 
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json 
      -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n 
      -Dcom.sun.management.jmxremote=true 
      -Dcom.sun.management.jmxremote.port=3002 
      -Dcom.sun.management.jmxremote.rmi.port=3003 
      -Djava.rmi.server.hostname=127.0.0.1 
      -Dcom.sun.management.jmxremote.authenticate=false 
      -Dcom.sun.management.jmxremote.ssl=false
    CACHE_REFRESH_MS_RATE: "60000"
    REDIS_CACHE_ENABLED: "true"