microservice-chart:
  image:
    repository: cstarucommonacr.azurecr.io/idpayrewardcalculator
    tag: latest
    pullPolicy: Always

  ingress:
    host: "uat01.idpay.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    aks-api-url: cstar-u-weu-uat01-aks-apiserver-url
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-u-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}

  envConfig:
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:+UseContainerSupport
      -Djava.security.egd=file:/dev/./urandom
      -javaagent:/app/applicationinsights-agent.jar 
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json
    CACHE_REFRESH_MS_RATE: "60000"
    REDIS_CACHE_ENABLED: "true"