name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

permissions:
  packages: write
  contents: write


jobs:
  checkout:
    name: 🔖 Checkout Repository
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          ref: ${{ github.ref_name }}

  flow-release:
    name: 🚀 Release
    runs-on: ubuntu-22.04
    needs: checkout
    steps:
      - name: 🚀 release + docker
        # https://github.com/pagopa/github-actions-template/releases/tag/v2.1.1
        uses: pagopa/github-actions-template/payments-flow-release@e67e0ec4bb01d6cb5065e311ba0e1c92c49966a7
        with:
          current_branch: ${{ github.ref_name }}
